### ISSUE TITLE
Vectorisers.go only tokenise for a-Z languages.

### ISSUE THREAD

**Issue by ThomasK81** [james-bowman/nlp#5]
Hi, 

Thanks for your hard work. I really like your code base. I have noticed that the package as is only works for languages that can be expressed in a-Z alphabets and, in addition, the hardcoded stop words make it a bit challenging for even historic or fringe English corpora. I have a fix for both. But did not want to PR without creating the issue first and see if you want to open up the project for non-English, historic English, and non a-Z languages. 

Thanks again!

Best, 

Thomas

**Comment by james-bowman** [comment]
Hi Thomas, thanks.  Expanding support for other languages, historic or specialist English corpora would be fantastic.  PRs would be very welcome, indeed.

Regards

James

**Comment by ThomasK81** [comment]
Great. I have created a PR. Let me know what you think. 

Regards, 

Thomas

**Comment by james-bowman** [comment]
PR #6 Merged - thanks.
